### ISSUE TITLE
Sorry I have no issue just Need to Contact You on Urgent Basis

### ISSUE THREAD

**Issue by atharao** [pakistanimoon/epikp-laravel#2]
Subject: Seeking Assistance with Your Open Source Project for My Final Year B.Tech Project

Dear Imran Qamer sir,

I hope this email finds you well. My name is  Rao Athar Khan and I am a final-year B.Tech student. I am reaching out to express my deep admiration for your open-source project,

As part of my final year academic requirement, I am keen on taking on Blockchain as my B.Tech project. I believe working on such a significant and valuable project will not only enhance my skills but also contribute to the open-source community.

However, I have encountered some difficulties when attempting to run the project on my local machine. I have followed the installation and setup instructions diligently, but I am facing challenges in getting it to work properly.

I understand that your time is valuable, but I was wondering if it would be possible for you or any of the project's developers to spare just 5 minutes for a quick call or chat to help me troubleshoot the issues I am facing. I am confident that with your guidance, I will be able to overcome the obstacles and proceed with my project successfully.

Please let me know if you are available for a brief discussion at your earliest convenience. I would be extremely grateful for any assistance you can provide.

Best regards,
Rao Athar Khan

Please Do Contact me 
EMAIL: raoathar.200@gmail.com
Whatsapp number: +91 9760087763

**Comment by pakistanimoon** [comment]
can you please share few of the issues which you are facing? as you mentioned "issues I am facing"

**Comment by atharao** [comment]
sir, I need your Guidance for the project Supply Chain using blockchain I know it is not your project you have forked it from Geekyants
but sir you have set up it on your computer you run that project but I am not able to run that project on my laptop due to the change in the network of Rinkeby also I m facing Port issues  and my other

it would be nice if you please take five minutes to explain how to run that on my laptop as I have to show it as my final-year project we can do a meeting on google meet if you are comfortable with that let me know

![image](https://github.com/pakistanimoon/epikp-laravel/assets/116030767/a8807ed8-66db-4bc8-9986-76b5789ea9ba)

**Comment by atharao** [comment]
Brother if You are not interested at least tell me I really need your help with this
